[project]
name = "just-config-mixin"
dynamic = ["version"]
description = "Yet another config mixin/manager."
authors = [{ name = "guest400123064", email = "wangy49@seas.upenn.edu" }]
packages = [{ include = "configmixin", from = "src" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "orjson (>=3.11.1,<4.0.0)",
    "pytest-cov>=7.0.0",
]

[dependency-groups]
dev = [
    "bpython>=0.25",
    "coverage>=7.9.2",
    "pdoc>=15.0.4",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "ruff>=0.12.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/configmixin/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/configmixin"]

[tool.coverage.run]
omit = ["tests/*"]
