[project]
name = "just-config-mixin"
version = "0.2.0a1"
description = "Yet another config mixin/manager."
authors = [{ name = "guest400123064", email = "wangy49@seas.upenn.edu" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "orjson (>=3.11.1,<4.0.0)",
]

[dependency-groups]
dev = [
    "bpython>=0.25",
    "coverage>=7.9.2",
    "pdoc>=15.0.4",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.12.4",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "configmixin"
module-root = "src"

[tool.coverage.run]
omit = ["tests/*"]
